[env:teensy41]
platform = teensy
board = teensy41
framework = arduino

monitor_speed = 115200

build_flags =
    -D USB_MIDI_AUDIO_SERIAL

lib_deps =
    https://github.com/adafruit/Adafruit_Seesaw
    https://github.com/adafruit/Adafruit_ILI9341
    https://github.com/adafruit/Adafruit-GFX-Library
    
lib_extra_dirs = lib
lib_ldf_mode = deep+