[env:teensy41]
platform = teensy
board = teensy41
framework = arduino

monitor_speed = 115200

build_flags =
    -D USB_MIDI_AUDIO_SERIAL

lib_deps =
<<<<<<< HEAD
    https://github.com/adafruit/Adafruit_Seesaw
    https://github.com/adafruit/Adafruit_ILI9341
    https://github.com/adafruit/Adafruit-GFX-Library
=======
    adafruit/Adafruit Keypad @ ^1.3.0
    adafruit/Adafruit NeoPixel @ ^1.12.3
    paulstoffregen/Encoder @ ^1.4.4
    https://github.com/PaulStoffregen/SerialFlash.git
    https://github.com/adafruit/Adafruit_Seesaw
    https://github.com/adafruit/Adafruit_ILI9341
    https://github.com/adafruit/Adafruit-GFX-Library
    https://github.com/h4yn0nnym0u5e/Audio/tree/features/dynamic-updates
    https://github.com/crudlabs/StevesAwesomeButton
>>>>>>> a5e021157cc17178c5e9404fdbc1f1a78897f726

lib_extra_dirs = lib
lib_ldf_mode = deep+
